# Port, na kterém pob??í JEN tvá product-service (obejdeme Nginx)
server.port=8081

# P?ipojení na Postgres (mí?í na localhost port vystavený z Dockeru)
spring.datasource.url=jdbc:postgresql://localhost:5433/eshop-product-db
spring.datasource.username=user
spring.datasource.password=password

# Kafka pro lokální vývoj
spring.kafka.bootstrap-servers=localhost:9092

# Elasticsearch (zatím p?ipravené)
spring.elasticsearch.uris=http://localhost:9200